version: 1.0.1
name: hole-docker

services:
  redis_db:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  mysql_db:
    container_name: mysql
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
