version: 1.0.1
name: hole-docker

services:
  redis_db:
    container_name: cache
    image: redis:latest
    ports:
      - "6379:6379"

  mysql_db:
    container_name: mysql
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

#  file_service:
#    container_name: "file_service"
#    image: minio/minio
#    ports:
#      - "9000:9000"
#      - "9090:9090"
#    command:
#      - server /data
#    environment:
#      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
#      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY